### ISSUE TITLE
Project setup kanban board

### ISSUE THREAD

**Issue by thecodechaser** [thecodechaser/things-catalog#26]
### For this project we are three team members:
1. Ranjeet Singh: @thecodechaser as Team member 1
2. Claude Mucyo: @Mucyosoda as Team member 2
3. Mohamed Elshamy: @mohamedelshamy55 as Team member 3

### Link to the Github project [Kanban Borad](https://github.com/thecodechaser/catalog-of-my-things/projects/1)

**Comment by dasileker** [comment]
### **Hi @thecodechaser @mohamedelshamy55 @Mucyosoda,** 

### **Good job so far!**
You still need to work on some issues to go to the next project, but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

- nice job on setting your kanban board cards, but the points are not equally distributed you shouldn't have a 5 points difference.

![Capture web_14-3-2022_105550_gitlab com](https://user-images.githubusercontent.com/61562626/158148899-9c88e807-c689-446a-b3c5-6409e191c63b.jpeg)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
### **Hi @thecodechaser @mohamedelshamy55 @Mucyosoda ,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
